config/routes.rb
BandMan::Application.routes.draw do
  
  
  root :to => "pages#home"
  
  resources :contacts
  resources :users

  match "signup" => "users#create", :as => "signup_create", :via => :post
  match "signup" => "users#new", :as => "signup"
  match "signup/validate/email" => "users#email_unique", :as => "signup_validate_email"

  match "login" => "session#create", :as => "login_create", :via => :post
  match "login" => "session#new", :as => "login"
  match "logout" => "session#destroy", :as => "logout"

  match "dashboard" => "dashboard#index", :as => "dashboard"

  match "i18n/all" => "i18n#all", :as => "i18n"
  match "i18n/validations" => "i18n#validation", :as => "i18n_validation"

  match ":band_id" => "bands#show", :as => "band"
  resources :bands, :path => '', :except => [:index, :create, :new, :show] do
  
    resources :todos, :controller => "TodoGroups", :as => "todo_groups" do
      
      resources :items, :controller => "Todos", :as => "todos" do

        match "status" => "todos#get_statuses", :via => :get, :As => "status"
        match "status" => "todos#create_status", :via => :post, :as => "create_status"

        resources :comments

      end

    end

  end

end

app/models/band.rb
class Band < ActiveRecord::Base

	has_many :band_memberships, :foreign_key => :band_id
	has_many :users, :through => :band_memberships, :foreign_key => :band_id

	has_many :band_genres, :foreign_key => :band_id
	has_many :genres, :through => :band_genres, :foreign_key => :band_id

	has_many :todo_groups, :dependent => :destroy


	def to_param
		"#{id}-#{bandname.parameterize}"
	end

end

app/models/band_genres.rb
class BandGenres < ActiveRecord::Base

	belongs_to :genres
	belongs_to :bands

	
end

app/models/band_membership.rb
class BandMembership < ActiveRecord::Base

	belongs_to :band
	belongs_to :user

end

app/models/comment.rb
class Comment < ActiveRecord::Base

	JSON_OPTIONS = { 
		:include => [:user => User::JSON_OPTIONS ],
		:methods => [:message_html],
		:except => [:commentable_id, :commentable_type, :user_id]
	}

	belongs_to :user
	belongs_to :commentable, :polymorphic => true

	before_create :set_current_user



	def as_json(options = {})
		super options.merge(JSON_OPTIONS)
	end

	private
	def set_current_user

		self.user = User.current

	end

end

app/models/contact.rb
class Contact < ActiveRecord::Base

	def fullname
		return self.firstname + " " + self.lastname
	end

end

app/models/entity.rb
class Entity < ActiveRecord::Base
end

app/models/genres.rb
class Genres < ActiveRecord::Base

	default_scope order("genre asc")

end

app/models/todo.rb
class Todo < ActiveRecord::Base

	JSON_OPTIONS = { 
		:methods => [:to_param, :comments_count, :status, :groupinfo],
		:except => [:todo_group_id],
		:include => [:todo_statuses => TodoStatus::JSON_OPTIONS]
	}


	belongs_to :todo_group, :foreign_key => :group_id

	has_many :comments, :as => :commentable
	has_many :todo_statuses, :foreign_key => :todo_id, :dependent => :destroy

	default_scope order("sortorder asc")

	before_create :create_status

	def to_param
		"#{id}-#{title.parameterize}"
	end	


	def status
		self.todo_statuses.last
	end
	def group
		self.todo_group
	end
	
	def comments_count
		self.comments.count
	end

	def groupinfo 
		{
			:id => self.todo_group.id,
			:title => self.todo_group.title,
			:to_param => self.todo_group.to_param
		}
	end


	def as_json(options = {})

		super options.merge(
			JSON_OPTIONS
		)

	end

	private
	def create_status

		status = self.todo_statuses.new
		status.completed = false
		status.in_progress = false
		status.save

	end

end

app/models/todo_group.rb
class TodoGroup < ActiveRecord::Base

	belongs_to :band
	has_many :todos, :dependent => :destroy, :foreign_key => :group_id

	def to_param
		"#{id}-#{title.parameterize}"
	end

	def as_json(options = {})

		super options.merge(
			:include => [:todos => Todo::JSON_OPTIONS],
			:methods => [:to_param]
		)

	end

end

app/models/todo_status.rb
class TodoStatus < ActiveRecord::Base

	JSON_OPTIONS = {
		:except => [:todo_id, :updated_at],
		:include => [:user => User::JSON_OPTIONS]
	}

	belongs_to :todo
	belongs_to :user

	before_create :add_user

	default_scope order("created_at ASC")


	def as_json(options = {})

		super options.merge(JSON_OPTIONS)

	end

	private
	def add_user		
		self.user = User.current
	end

	

end

app/models/user.rb
class User < ActiveRecord::Base

	# Json Parsing
	JSON_OPTIONS = { 
		:except => [:password_digest, :activated_at, :activation_code, :lastlogin_at, :preferred_locale, :updated_at, :created_at, :avatar_content_type, :avatar_file_name, :avatar_file_size, :avatar_updated_at],
		:methods => [:fullname, :avatar_thumb]
	}

	# Public static accessor to get current user
	cattr_accessor :current, :instance_accessor => false
	
	# Relationships
	belongs_to :contact, dependent: :destroy
	accepts_nested_attributes_for :contact

	has_many :band_memberships, :foreign_key => :user_id
	has_many :bands, :through => :band_memberships

	has_many :todos, :foreign_key => :created_by
	has_many :todo_statuses

	attr_accessible :email, :password, :password_confirmation, :preferred_locale, :date_lastlogon, :contact_attributes, :contact, :bands, :avatar

	# Avatar image
	has_attached_file :avatar, :styles => { 
		:medium => ["300x300>", :png], 
		:thumb => ["50x50>", :png]
	}, :default_url => "/assets/avatars/:style/missing.png"
	
	# Authentication
	has_secure_password

	# Validation
	validates :email, presence: true, uniqueness: true
	#validates :password, presence: true

	# Filters
	before_save :copy_email_to_contact



	def self.current
		Thread.current[:user]
	end
	def self.current=(user)
		Thread.current[:user] = user
	end

	def fullname
		self.contact.fullname
	end


  	def as_json(options = {})
		super options.merge(JSON_OPTIONS)
	end
  
	def avatar_thumb
		self.avatar.url(:thumb)
	end

	def avatar_medium
		self.avatar.url(:medium)
	end

	
  	private
  	def copy_email_to_contact
  		self.contact.email = self.email
  	end


end

app/controllers/todo_groups_controller.rb
class TodoGroupsController < ApplicationController
  

  # GET /todo_groups
  # GET /todo_groups.json
  def index
    
    @todo_groups = @current_band.todo_groups.all

    respond_to do |format|
      format.js { render :js, :partial => "todo_groups/js/todos", :content_type => "text/javascript" }
      format.html { render "todo_groups/index" } # index.html.erb
      format.json { render json: @todo_groups }
    end

  end

  # GET /todo_groups/1
  # GET /todo_groups/1.json
  def show
    @todo_group = TodoGroup.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @todo_group }
    end
  end

  # GET /todo_groups/new
  # GET /todo_groups/new.json
  def new
    @todo_group = TodoGroup.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @todo_group }
    end
  end

  # GET /todo_groups/1/edit
  def edit
    @todo_group = TodoGroup.find(params[:id])
  end

  # POST /todo_groups
  # POST /todo_groups.json
  def create
    @todo_group = TodoGroup.new(params[:todo_group])

    respond_to do |format|
      if @todo_group.save
        format.json { render json: @todo_group, status: :created }
      else
        format.json { render json: @todo_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /todo_groups/1
  # PUT /todo_groups/1.json
  def update
    @todo_group = TodoGroup.find(params[:id])

    respond_to do |format|
      if @todo_group.update_attributes(params[:todo_group])
        format.html { redirect_to @todo_group, notice: 'Todo group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @todo_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_groups/1
  # DELETE /todo_groups/1.json
  def destroy
    @todo_group = TodoGroup.find(params[:id])
    @todo_group.destroy

    respond_to do |format|
      format.html { redirect_to todo_groups_url }
      format.json { head :no_content }
    end
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/band_helper.rb
module BandHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/i18n_helper.rb
module I18nHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/todo_groups_helper.rb
module TodoGroupsHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/todo_groups/_form.html.erb
<%= form_for(@todo_group) do |f| %>
  <% if @todo_group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo_group.errors.count, "error") %> prohibited this todo_group from being saved:</h2>

      <ul>
      <% @todo_group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :band %><br />
    <%= f.text_field :band %>
  </div>
  <div class="field">
    <%= f.label :created_by %><br />
    <%= f.text_field :created_by %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :order %><br />
    <%= f.text_field :order %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/todo_groups/_new-form.html.erb
<div class="form ajax folding rich small form-add-todo-list">

	<h2 class="folding-title"><div class="icon plus"></div><%= t "frontend.todo_groups.new.title" %></h2>

	<div class="folding-content">

		<%= form_for :todo_group, :url => band_todo_groups_path, :html => { :class => "rich" } do |f| %>
		  
			<%= f.hidden_field :band_id, :value => @current_band.id %>

			<div class="field">
				<%= f.label :title, t("frontend.todo_groups.title.label") %>
		    	<%= f.text_field :title, 
		    			:placeholder => t("frontend.todo_groups.title.placeholder"),
						"data-validate" => "min-length: 2"
				%>
			</div>

			<div class="field">
				<%= f.label :description, t("frontend.todo_groups.description.label") %>
		    	<%= f.text_area :description, 
		    			:placeholder => t("frontend.todo_groups.description.placeholder"),
						"data-validate" => "optional: true"
				%>
			</div>

			<div class="actions">
				<a href="#" class="button main-action submit"><%= t "frontend.todo_groups.new.submit" %></a>
			</div>

		<% end %>

		<div class="form-complete">

			<%= t "frontend.todo_groups.new.complete" %> <a href="#" class="reset-form"><%= t "frontend.todo_groups.new.resetlink" %></a>.

		</div>

	</div>

</div>

app/views/todo_groups/_new-todo-form.html.erb
<div class="form ajax rich form-add-todo">

	<div class="icon plus"></div>
	<div class="click-header">
		<%= t "frontend.todos.new.header" %>
	</div>

	<%= form_for :todo, :html => { :class => "rich" } do |f| %>

		<div class="field">
			<%= f.text_field :title, 
	    			:placeholder => t("frontend.todos.new.title.placeholder"),
					"data-validate" => "min-length: 2"
			%>
		</div>

	<% end %>
</div>

app/views/todo_groups/_todo-group.html.erb
<% content_for :javascript_includes do %>
	<%= javascript_include_tag band_todo_groups_path + ".js" %>
<% end %>

<div class="todos ajax-content" data-source="<%= request.fullpath %>">	
</div>

app/views/todo_groups/edit.html.erb
<h1>Editing todo_group</h1>

<%= render 'form' %>

<%= link_to 'Show', @todo_group %> |
<%= link_to 'Back', todo_groups_path %>

app/views/todo_groups/index.html.erb
<div class="main-content">

	<%= render :partial => "todo-group" %>
	<%= render :partial => "new-form" %>

</div>
<div class="sidebar">

	<%= render :partial => "sidebar" %>

</div>

app/views/todo_groups/js/_todos.js.erb
$(document).ready(function(){

	// Instantiate global object
	$.todos = {};
	$.todos.target = $(".content .todos");
	
	// Load todo's
	$.todos.load = function() {

		// Get data source
		var sUrl = $.todos.target.attr("data-source");

		// Empty and set to loading
		$.todos.target.empty().addClass("loading");


		// Load 
		$.ajax({

			url: sUrl,
			dataType: "json"

		}).then(function(result) {

			// Is result wrapped in an array, or a single item?
			if (!$.isArray(result)) {
				
				// Add single one
				$.todos.addList(result);

			} else {

				// Loop through result and add 'em
				$.each(result, function(index, list) {
					$.todos.addList(list);
				});

			}
			
		}).fail(function(result) {

			// Show error
			alert("ERROR");

		}).done(function() {

			// No longer loading.
			$.todos.target.removeClass("loading");

		});
		

	};

	// Add to-do list
	$.todos.addList = function(oList) {

		// Create main object
		var $list = $("<div>").addClass("todo-list").data("todoList", oList);
			
		// Create title
		var $title = $("<h2>")
			.append(
				$("<a>")
					.attr("href", Routes.band_todo_group_path('<%= @current_band.to_param %>', oList.to_param))
					.html(oList.title)
			)
			.appendTo($list);

		// Description?
		if (oList.description !== "") {
			var $description = $("<span>")
					.addClass("description")
					.html(oList.description)
					.appendTo($list);
		}

		// Create listing
		var $table = $("<table>").appendTo($list);

		// Any items?
		if (typeof oList.todos === "object") {

			// Loop and add
			$.each(oList.todos, function(index, todo) {

				$.todos.addTodo($list, todo);

			});

		}
		


		// Add todo-item form
		var $addForm = $("<%= escape_javascript(render :partial => "new-todo-form" ) %>")
					.appendTo($list);

		// Set action for this form
		$addForm.find("form")
			.attr("action", Routes.band_todo_group_todos_path('<%= @current_band.to_param %>', oList.to_param))

		// Add hidden field for the group id
		.prepend(
			$('<input type="hidden" name="todo[group_id]" value="' + oList.id + '">')
		);

		// Activate the form
		$addForm
			.ajaxForm()
			.richForm()
			.bind("success", function(e, oTodo) {

				// Add the item :)
				$.todos.addTodo($list, oTodo);

				// Reset the form
				$addForm.ajaxForm("reset");

			})
			.bind("error", $.bandman.onError);

		// Add click/hide behavior
		$addForm.bind("click", function(e) {

			// Switch
			$addForm.toggleClass("active", true).find("input").focus();

		}).find("input").bind("blur", function() {

			// Switch back
			$addForm.toggleClass("active", false);

		});

	
		// Append to page
		$.todos.target.append($list);

	};
	
	$.todos.addTodo = function($list, oTodo) {

		// Get list info
		var oList = $list.data("todoList");

		// Find UL
		var $table = $list.find("table");

		// Create item
		var $row = $("<tr>")
						.addClass("todo")
						.data("todo", oTodo),

		// Dragger
		$dragger = $("<td>")
						.addClass("dragger")
						.html(' ')
						.appendTo($row),

		// Checkbox
		$check = $("<td>")
						.addClass("check")
						.html(" ")
						.appendTo($row),
		$checkIcon = $("<div>")
						.addClass("icon")
						.appendTo($check),

		// Title
		$title = $("<td>")
						.addClass("title")
						.html(oTodo.title)
						.appendTo($row),

		

		// Comments
		$comments = $("<td>")
						.addClass("comments")
						.appendTo($row),
		$commentsLink = $("<a>")
						.attr("href", Routes.band_todo_group_todo_path('<%= @current_band.to_param %>', oList.to_param, oTodo.to_param))
						.appendTo($comments)
		$commentsAttachment = $("<div>")
						.addClass("icon")
						.addClass("attachment")
						.appendTo($commentsLink),
		$commentsIcon = $("<div>")
						.addClass("icon")
						.addClass("comment")
						.appendTo($commentsLink),
		$commentsCaption = $("<span>")
						.html(I18n.t("frontend.comments.number_of_comments", {count: oTodo.comments_count } ))
						.appendTo($commentsLink),

		// Delete
		$delete = $("<td>")
						.addClass("delete")
						.appendTo($row),
		$deleteIcon = $("<div>")						
						.addClass("icon")
						.addClass("delete")
						.appendTo($delete);

		// Apply current status
		$row
			.toggleClass("in_progress", oTodo.status.in_progress)
			.toggleClass("complete", oTodo.status.completed);


		// Check click behavior
		$checkIcon.bind("click", function(e) {

			// Add busy class
			if ($row.hasClass("busy")) return;
			$row.addClass("busy");

			// Get data object
			var oTodo = $row.data("todo"),
				bInProgress,
				bComplete;

			// Neither?
			if (oTodo.status.in_progress === false && oTodo.status.completed === false) {

				// Set to in progress
				bInProgress = true;	
				bComplete = false;
				
			} else if (oTodo.status.in_progress === true) {

				// Set to complete
				bInProgress = false;
				bComplete = true;
				
			} else if (oTodo.status.completed === true) {

				// Set to reset
				bInProgress = false;
				bComplete = false;
				
			}

			// Submit it to the server
			$.ajax({

				url: Routes.band_todo_group_todo_status_path('<%= @current_band.to_param %>', oList.to_param, oTodo.to_param),
				type: "post",
				dataType: "json",
				data: {
					todo_status: {
						completed: bComplete,
						in_progress: bInProgress
					}
				}

			}).then(function(result) {

				// Add result to todo's statuses
				oTodo.todo_statuses.unshift(result);
				oTodo.status = result;
				$row.data("todo", oTodo);

				// Apply it
				$row
					.toggleClass("in_progress", result.in_progress)
					.toggleClass("complete", result.completed);

			}).fail(function(result) {

				// 
				alert("ERROR :(");

			}).done(function() {

				// No longer busy
				$row.removeClass("busy");

			});

			console.log(bInProgress, bComplete);


		});



		// Add it
		$table.append($row);


	}	


	// Add behavior to add form
	$(".form-add-todo-list").bind("success", function(e, result) {

		// Add it!
		$.todos.addList(result);

	});


	// Load to-do's now
	$.todos.load();


});

app/views/todo_groups/new.html.erb
<h1>New todo_group</h1>

<%= render 'form' %>

<%= link_to 'Back', todo_groups_path %>

app/views/todo_groups/show.html.erb
<div class="main-content">

	<%= render :partial => "todo-group" %>

</div>
<div class="sidebar">

	<%= render :partial => "sidebar" %>

</div>